# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_auto_20180725_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
