# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20180725_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.Profile'),
        ),
    ]
