# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_auto_20180727_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
